[package]
name = "ray-tracer"
version = "0.1.0"
edition = "2021"
default-run = "ray-tracer"

[lib]
name = "lib_ray_tracer"

[[bin]]
name = "ray-tracer"

[[bin]]
name = "projectile"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
